# Generated by Django 3.1.4 on 2021-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtofav',
            name='city_name',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtofav',
            name='place_name',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
